BACKUP DATABASE [OPSBATCH] TO  DISK = N'H:\20170525 Backups\OPSBATCH.bak' WITH NOFORMAT, NOINIT,  NAME = N'OPSIMPORT-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

BACKUP DATABASE [OPSIMPORT] TO  DISK = N'H:\20170525 Backups\OPSIMPORT.bak' WITH NOFORMAT, NOINIT,  NAME = N'OPSIMPORT-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

BACKUP DATABASE [OPSPORTAL] TO  DISK = N'H:\20170525 Backups\OPSPORTAL.bak' WITH NOFORMAT, NOINIT,  NAME = N'OPSIMPORT-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

